### ISSUE TITLE
Doubt: Are the public nodes free to use?

### ISSUE THREAD

**Issue by blacklightpy** [OpenDroneMap/CloudODM#12]
I know that there is a free trial to use Lightning Network on the spark1 node.

But I saw CloudODM by default choses one of the publicly available nodes. Does it mean that when not in use by anyone, spark1 node is available for free?

EDIT: Decided to move to the forum.
EDIT2: Not sure where the appropriate section is to ask the question

**Comment by smathermather** [comment]
That's a good forum question for now. Thanks @blacklightpy!
