### ISSUE TITLE
Task begun via ODM cmdlet not showing on WebODM Lightning Dashboard

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/CloudODM#8]
I logged into the default cluster, signed into WebODM Lightning with my account credentials, and began a project by uploading data with all default settings (except I passed --verbose) to monitor activity.

When I log into WebODM Lightning dashboard using the same account credentials, I do not see any activity in the dashboard, nor the project when checking the WebUI.

Is this expected behavior?

**Comment by pierotofy** [comment]
Hey @Saijin-Naib  :hand: this is expected; the WebUI is not aware of tasks you might have sent with CloudODM. Thanks for reporting it though!

**Comment by Saijin-Naib** [comment]
Piero,

Thanks for confirming that this is not a bug.

Do you see value in potentially changing this behavior in the future? Is that even possible?

Thanks!

**Comment by pierotofy** [comment]
Yes it's possible, although not straightforward to implement. Definitely something we'll consider adding in the near future.

**Comment by pierotofy** [comment]
I suppose. I've opened it in the proper repository. https://github.com/OpenDroneMap/NodeODM/issues/97

**Comment by Saijin-Naib** [comment]
Thanks and sorry. Still trying to learn where I should open tickets for the various subsystems. A bit muddy to me, yet.

**Comment by pierotofy** [comment]
No worries, thanks for the feedback!

**Comment by smathermather** [comment]
> Thanks and sorry. Still trying to learn where I should open tickets for the various subsystems. A bit muddy to me, yet.

Sometimes I don't know which is the correct repo. :) Thanks for thinking about ways to improve!
